microservice:
  student-service:
   endpoints:
     endpoint:
      uri: http://API-GATEWAY/college/findAll
  student-service:
   endpoints:
     endpoint:
      fiegn:
       uri: http://API-GATEWAY/feign/findAllUsers    
      
  college-service:
    endpoints:
     endpoint:
       uri: http://API-GATEWAY/student/findAll
