eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  student-service:
   endpoints:
     endpoint:
      uri: http://API-GATEWAY/college/findAll
  college-service:
    endpoints:
     endpoint:
       uri: http://API-GATEWAY/student/findAll
